### ISSUE TITLE
Mudança de data

### ISSUE THREAD

**Issue by jlcarvalho** [frontendgoias/FrontInGoiania#11]
Pessoal, inicialmente tínhamos programado a data do evento para o dia 12 de Setembro, no entanto no mesmo dia ocorrerá o Encontro Nacional de Mulheres na Tecnologia, como exposto pela @marcianeoqav no tópico de voluntários https://github.com/frontendgoias/FrontInGyn/issues/6#issuecomment-121295600.

Ainda em Setembro, no dia 26 o acontecerá DevFest Goiás organizado pelo GDG Goiânia, logo, teremos três eventos locais no mesmo mês. A concorrência desses eventos pode comprometer o público dos mesmos. E o objetivo desse evento é fortalecer a comunidade de desenvolvimento local e não trazer concorrência aos eventos já existentes.

Portanto, acredito que a melhor opção é alterarmos a data de nosso evento. Por isso estou abrindo essa issue. Aqui poderemos discutir uma melhor data para o Front In Goiânia para que o evento possa beneficiar o ecossistema local da melhor maneira possível.

cc: @diogobeda, @fabricionaweb

**Comment by renanmorais** [comment]
Puxa pra agosto tem como nao ???

**Comment by jlcarvalho** [comment]
Acho difícil adiantar o evento @renanmorais, por que a programação de organização do evento estava planejada para o dia 12 de Setembro. Então as artes, a busca de patrocínios, a venda de ingressos estava cronometrada pra essa data. Se adiantarmos provavelmente não conseguiremos fazer o evento com a qualidade planejada por falta de tempo.

**Comment by marcianeoqav** [comment]
Até referente a patrocínio poderíamos ter conflitos. O que acham de Outubro? Outra coisa é que em meados de 20 e 21 de Novembro terá o Fórum Goiano de Software Livre e durante a semana vai rolar outros eventos em parceria com mesmo (ERI-GO, IME, ENGI...) aproveitando a infraestrutura (UFG - Centro de Aulas D). Outra opção seria propor uma parceria tbm.

**Comment by villander** [comment]
Cara coloca em outubro que você como integrando do GDG pode fazer uma propaganda lá e captar mais espectadores, já que o front seria no mês seguinte

**Comment by jlcarvalho** [comment]
O que vocês acham do dia 3 de Outubro? Gostaria de definir isso hoje pois existe a possibilidade de conseguirmos o auditório do CCBEU pra essa data.

@renanmorais , @marcianeoqav , @fabricionaweb , @villander , @diogobeda

**Comment by marcianeoqav** [comment]
Por mim, ok!

**Comment by diogobeda** [comment]
Acho uma boa data tbm. :+1:

**Comment by fabricionaweb** [comment]
Por mim tudo bem. Em outubro tem o Front in Manaus mas acho que não atrapalha...

http://braziljs.org/eventos/

**Comment by villander** [comment]
Manaus só tem indio, ausdhfhudsuf

Fica massa essa data pra mim também mano

**Comment by renanmorais** [comment]
Ótima data, e melhor ainda já por ter o local liberado.

**Comment by jlcarvalho** [comment]
Então beleza, fica marcado para o dia 3 de Outubro. Vou marcar o tópico como fechado e prosseguir as negociações com o CCBEU.

**Comment by jlcarvalho** [comment]
Infelizmente tive que alterar a data do evento para o dia 10 de Outubro devido a disponibilidade do auditório do CCBEU.

**Comment by villander** [comment]
Lamentável @jlcarvalho

**Comment by marcianeoqav** [comment]
ok

**Comment by igorvieira** [comment]
A meu, o lance é ter o evento!
Eu estou super motivado por termos algo assim, sério!
E espero podermos realizar e fazer desse um evento memorável!
