### ISSUE TITLE
Valores

### ISSUE THREAD

**Issue by jlcarvalho** [frontendgoias/FrontInGoiania#4]
Como eu falei na issue a respeito do patrocínio, sem grana não tem evento. E nós precisamos cobrar pela entrada até por que não sabemos se conseguiremos patrocínio e/ou, caso consigamos, se o valor do patrocínio será o suficiente para bancar o evento de forma integral.

Portanto precisamos definir o valor dos ingressos. Lembrando que esse valor tem que ser revertido em benefícios para os participantes e que nossas contas serão transparentes, assim como toda a organização do evento.

**Comment by jlcarvalho** [comment]
O valor que eu sugiro para os ingressos é de `R$ 80,00`, após minha experiência com o DevFest percebi que o valor de R$ 50,00 é pouco para a organização de um grande evento.

Nós temos custos com comida, brindes, segurança, local, divulgação, etc. e no caso do DevFest, se não fosse o patrocínio do Google o evento não teria acontecido a R$ 50,00.

Claro que eu acredito que só poderemos definir o valor a ser cobrado após estimarmos todos os nossos custos.

**Comment by diogobeda** [comment]
Será que `R$80,00` não é um pouco salgado demais? Ainda mais pra uma primeira edição, onde o evento não está proven ainda. Sou adepto da idéia de começar pequeno e ir crescendo nos próximos anos.

**Comment by jlcarvalho** [comment]
No fundo eu acredito que esse valor vai refletir as escolhas que a comunidade fizer nos outros tópicos que precisam ser resolvidos (patrocínio, brindes, local, comida, etc.).

Eu também acho `R$ 80,00` meio salgado, mas acredito que com esse valor conseguimos fazer o evento acontecer mesmo se não conseguirmos patrocínio.

**Comment by VictorCamargo** [comment]
Concordo com o @diogobeda, acho que para um primeiro evento (Meu sonho isso acontecendo aqui em Goiânia), acho que R$ 80,00 é meio puxado.

**Comment by cezarpretto** [comment]
Realmente R$ 80,00 é meio salgado. Mas como o amigo @jlcarvalho falou isso tudo depende de outros fatores que ainda não estão definidos.

**Comment by jlcarvalho** [comment]
Então vamos fechar o valor em R$ 50,00, mesmo? Daí nós adequamos nossos custos a essa realidade. Devemos ter em mente que teremos cerca de 150 participantes e que teremos de pagar cerca de 10% para o sistema gerenciador de eventos, logo, iremos arrecadar cerca de **R$ 6.750**.

Esse valor não é muito, ainda precisaremos mandar fazer os brindes e pagar diversas outras despesas. Vou tentar discriminar tudo ainda hoje.

Provavelmente precisaremos de patrocínio.
